[book]
authors = ["Casey Cheng"]
language = "zh-CN"
multilingual = false
src = "src"
title = "note"

[preprocessor.toc]
command = "mdbook-toc"
renderer = ["html"]

[preprocessor.mermaid]
command = "mdbook-mermaid"

[output.html]
additional-js = ["mermaid.min.js", "mermaid-init.js"]
default-theme = "navy"