[book]
authors = ["Casey Cheng"]
language = "zh-CN"
multilingual = false
src = "src"
title = "note"

[preprocessor.toc]
command = "mdbook-toc"
renderer = ["html"]

[output.html]
default-theme = "navy"
git-repository-url = "https://github.com/YiGuan-z/note"
edit-url-template = "https://github.com/YiGuan-z/note/edit/main/{path}"

[output.html.fold]
enable = true
level = 0